name: "Setup Node"
description: "Install the right node version along with application dependencies"
inputs:
  node-version:
    description: "Node Version"
    required: true
    default: 20.x

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - uses: actions/cache@v3
      with:
        path: "**/node_modules"

        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - run: npm install --legacy-peer-deps --no-audit
      shell: bash
