name: Main CI

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Run static checks
    strategy:
      fail-fast: false
      matrix:
        check: [test, types, lint]

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: ./.github/actions/setup-deps
      - run: npm run ${{ matrix.check }}

  end-to-end-tests:
    timeout-minutes: 60
    name: "End to End Tests"
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/setup-deps

      - name: Get app version
        shell: bash
        run: echo "APP_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - run: npm run build
        name: Build app
        env:
          APP_VERSION: ${{ env.APP_VERSION }}

      - run: npm run deploy:cypress
        name: Deploy E2E environment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  test-deploy:
    runs-on: ubuntu-latest
    name: Test Deploy
    if: github.ref == 'refs/heads/main'

    needs: [end-to-end-tests, checks]
    steps:
      - uses: actions/checkout@v3
      - name: Setup job

        uses: ./.github/actions/setup-deps
      - name: Get App Version
        shell: bash
        run: echo "APP_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - run: npm run build
        env:
          APP_VERSION: ${{ env.APP_VERSION }}

      - run: npm run cdk -- deploy tnm-web-test-frontend-stack --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  prod-deploy:
    runs-on: ubuntu-latest
    name: Prod Deploy
    if: github.ref == 'refs/heads/main'
    needs: [end-to-end-tests, checks]
    steps:
      - uses: actions/checkout@v3
      - name: Setup job

        uses: ./.github/actions/setup-deps
      - name: Get App Version
        shell: bash
        run: echo "APP_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - run: npm run build
        env:
          APP_VERSION: ${{ env.APP_VERSION }}

      - run: npm run cdk -- deploy tnm-web-prod-frontend-stack --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
