name: Main CI

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Run static checks
    strategy:
      fail-fast: false
      matrix:
        check: [test, types, lint]

    steps:
      - uses: actions/checkout@v3
      - name: Setup job
        uses: ./.github/actions/setup-deps
      - run: npm run ${{ matrix.check }}

  build:
    runs-on: ubuntu-latest
    name: Run static checks
    strategy:
      fail-fast: false
      matrix:
        check: [test, types, lint]

    steps:
      - uses: actions/checkout@v3
      - name: Setup job
        uses: ./.github/actions/setup-deps
      - run: npm run ${{ matrix.check }}

      - name: Get App Version
        shell: bash
        run: echo "APP_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

  deploy-for-cypress:
    runs-on: ubuntu-latest
    name: Deploy For Cypress
    needs: [build, checks]
    steps:
      - uses: actions/checkout@v3
      - name: Setup job

        uses: ./.github/actions/setup-deps
      - name: Get App Version
        shell: bash
        run: echo "APP_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - run: npm run build
        env:
          APP_VERSION: ${{ env.APP_VERSION }}

      - run: npm run deploy:cypress

  cypress-run:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [deploy-for-cypress]

    container:
      image: bwainwrighttnm/cypress:latest
      options: --ipc=host

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node environment
        uses: ./.github/actions/setup-node-job

      - name: Run E2E tests
        uses: ./.github/actions/cypress
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          google-refresh-token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          chargebee-token: ${{ secrets.CHARGEBEE_TOKEN }}
          cognito-pool-id: eu-west-2_77z37j3Fb
          github-token: ${{ secrets.GITHUB_TOKEN }}
